refactor send-feedback in 2 scripts
- send_status for status change
- send_comment to send a comment
- remove hardcoded repo names in alert

Change-Id: I8729534369920ebae02a40b40c13edd2fbdb93ca

diff --git a/tools/dci-pipeline-check b/tools/dci-pipeline-check
--- a/tools/dci-pipeline-check
+++ b/tools/dci-pipeline-check
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (C) 2022-2023 Red Hat, Inc.
+# Copyright (C) 2022-2024 Red Hat, Inc.
 #
 # Licensed under the Apache License, Version 2.0 (the "License"); you may
 # not use this file except in compliance with the License. You may obtain
@@ -161,7 +161,7 @@ esac
 if [ -d "$DIR" ]; then
     jobid="$(dci-queue searchdir $QUEUE $DIR)"
     if [ -z "$jobid" ]; then
-        "$BASEDIR/send-feedback$SUFFIX" $DIR "ERROR A job is already scheduled or running in $DIR (unable to find job id). Aborting."
+        "$BASEDIR/send_status$SUFFIX" "$DIR" error "ERROR A job is already scheduled or running in $DIR (unable to find job id). Aborting."
         exit 1
     fi
     "dci-queue" unschedule "$QUEUE" "$jobid"
@@ -249,7 +249,7 @@ else
         esac
     done
     if [ -z "$first_pipeline" ]; then
-        "$BASEDIR/send-feedback$SUFFIX" "$DIR" "ERROR unable to find a pipeline file" 1>&2
+        "$BASEDIR/send_status$SUFFIX" "$DIR" error "ERROR unable to find a pipeline file" 1>&2
         rm -rf $DIR
         exit 1
     fi
@@ -266,7 +266,7 @@ else
     done
 
     if [ -z "$RES" ]; then
-        "$BASEDIR/send-feedback$SUFFIX" "$DIR" "ERROR Unable to start a job on distributed-ci.io: no matching cluster_name (${cluster_names[*]}) for queue $QUEUE" 1>&2
+        "$BASEDIR/send_status$SUFFIX" "$DIR" error "ERROR Unable to start a job on distributed-ci.io: no matching cluster_name (${cluster_names[*]}) for queue $QUEUE" 1>&2
         rm -rf $DIR
         exit 1
     fi
@@ -319,7 +319,7 @@ if [ -d "$DIR.bootstrap" ]; then
 fi
 
 if [ "$RES" = "@RESOURCE" ]; then
-    "$BASEDIR/send-feedback$SUFFIX" "$DIR" "QUEUED" pending
+    "$BASEDIR/send_status$SUFFIX" "$DIR" pending "QUEUED"
     $CMD "${OPT[@]}"
     "dci-queue" list "$QUEUE"
 else
