send-feedback - allow to send unable to rebase message
With the current code, if a rebase error happens, the error message related to the rebase issue is not being sent, and it could be interesting for cases such as cnf-certification-test repository, just to let them now that a specific error may be because of a failed rebase.

Change-Id: I06d15d2102f1953b0d57ab6791c0243648725b66

diff --git a/tools/send-feedback b/tools/send-feedback
--- a/tools/send-feedback
+++ b/tools/send-feedback
@@ -71,10 +71,17 @@ for json in $(ls $DIR/*.json); do
                 if ! [[ "$DCI_URL" =~ ^http.* ]]; then
                     DCI_URL=
                 fi
-                # when no DCI job is found
+
+                # when no DCI job is found, extract the status
                 if [ -z "$DCI_URL" ]; then
                     DCI_STATUS=$(echo -e "$BODY"|grep -E "^(SUCCESS|ERROR|FAILURE|KILLED)")
-                    DCI_STATUS=$(echo -e "$BODY"|sed -e '/- /d' | grep -Eo "^(SUCCESS|ERROR|FAILURE|KILLED)")
+
+                    # however, avoid this DCI_STATUS var update if the original DCI_STATUS contains a
+                    # reference to "unable to rebase" issue, just to send the very same message
+                    REBASE_MSG="unable to rebase"
+                    if ! [[ "$DCI_STATUS" =~ .*"$REBASE_MSG".* ]]; then
+                        DCI_STATUS=$(echo -e "$BODY"|sed -e '/- /d' | grep -Eo "^(SUCCESS|ERROR|FAILURE|KILLED)")
+                    fi
                 fi
                 case "$DCI_STATUS" in
                     SUCCESS*)
